# Generated by Django 4.1.1 on 2022-09-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=1, max_length=200, verbose_name='موبایل'),
            preserve_default=False,
        ),
    ]
