# Generated by Django 4.1.1 on 2022-09-06 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Member',
        ),
    ]
